"""add user storage column

Revision ID: ee5a5b163f34
Revises: d4e5f6a7b8c9
Create Date: 2026-05-29 12:32:24.530925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee5a5b163f34"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = (
    "d4e5f6a7b8c9"  # pragma: allowlist secret
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("current_resources_storage_size", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "current_resources_storage_size")
    # ### end Alembic commands ###
